### ISSUE TITLE
Email Sharing: wrong mailto Link

### ISSUE THREAD

**Issue by m-glutting** [kevinbazira/algori-social-share-buttons-lite#1]
First of all, thanks for creating this cool Plugin!

We found one problem while using the email sharing button. This creates a link which follows this pattern:

mailto:body=<LINK_TO_ARTICLE>

This link opens the mail client and prefills the recipient field with everything after mailto:. The desired behavior would be to only have the link to the article in the mail body whilst the recipient field remains empty. This can be achieved if the mailto link has a ? between the : and the link to the article.
Therefore, the pattern should be:

mailto:?body=<LINK_TO_ARTICLE>

**Comment by kevinbazira** [comment]
Hi @m-glutting,

Thanks for your interest in the Algori Social Share Buttons plugin.

We have fixed the email sharing link issue.

Kindly download the latest version of Algori Social Share Buttons, the email sharing link should work as desired.

In case of any further inquiries please feel free to ask. I'll be happy to help.

Thanks
